### ISSUE TITLE
Address Certik claim that we are leaving tokens in pool

### ISSUE THREAD

**Issue by EGreg** [Intercoin/TradedTokenContract#14]
1. Find out what they want in terms of leaving tokens on the pool, and let’s consider the formulas they suggest. Let’s compare the formulas in the webpage they sent, to ours.
2. Or tell me if your formulas really leave practically zero tokens on both Traded and Reserve side. If so, let’s prove it to them, and ask them to produce a counterexample!

**Comment by artman325** [comment]
made via point1 and apply formula from https://blog.alphaventuredao.io/onesideduniswap/
did in [commit](https://github.com/Intercoin/TradedTokenContract/commit/7343bf19fa7f86a9b5d5db499ca5f9336335ee32)
There are no tokens left for now
