### ISSUE TITLE
Implement Anti-Dump feature

### ISSUE THREAD

**Issue by EGreg** [Intercoin/TradedTokenContract#15]
It's pretty simple. We want some addresses (especially PancakeSwap) to be designated that people can only send 5% of their balance per week there, for example.

Here is the outline of the code:

```
struct RateLimit {
  uint32 duration; // for time ranges, 32 bits are enough, can also define constants like DAY, WEEK, MONTH
  uint 32 fraction; // out of 100,000
}

function setRateLimit(address recipient, struct rateLimit) {
   if (msg.sender != recipient && msg.sender !== owner() && msg.sender != Ownable(recipient).owner) {
       throw new NotAuthorized();
   }
   rateLimit[recipient] = rateLimit;
}

private mapping (address => uint32) _alreadySentInCurrentBucket; // finally, a private mapping!
private mapping (address => uint64) _lastBucketTime;

function _transfer(from, to, amount) {
   // somewhere in this function
   uint256 currentBalance = balanceOf(from);
   uint256 max = currentBalance * rateLimit[to] / 100000;
   uint32 duration = rateLimit[to].duration;
   if (block.time / duration * duration > lastBlockTime) {
      _lastBucketTime[to] = block.time;
      _alreadySentInCurrentBucket = 0;
   }
   if (_alreadySentInCurrentBucket[to] + amount <= max) {
      // proceed with transfer normally
   } else {
      // exceeded rate limit. But we control the token and how much gets transferred,
      // so let's just transfer whatever is left, and UniSwap will have to use the FeeOnTransfer method versions
      _alreadySentInCurrentBucket[to] = max;
      transfer only max - _alreadySentInCurrentBucket[to];
}
```

1. We need to test that UniSwap with FeeOnTransfer methods can handle this
2. Also, people can probably circumvent this by receiving a lot of tokens to make their balance larger, then sending 5% to the PancakeSwap, and then sending it to the next guy. We should discuss how to prevent such cheating.

**Comment by artman325** [comment]
due to [claiming issue](https://github.com/Intercoin/TradedTokenContract/issues/12#issuecomment-1351806284)
 there was full predictability of limits for the public !!!

**Comment by EGreg** [comment]
We should reopen it. Anti dump feature is different from claiming limits.

When enabled, it would prevent ANYONE from selling more than 5% of their tokens to some specific addresses such as pancake pools.

This prevents THE PUBLIC ALSO from panic-selling. People might panic-sell for example if insiders or whales sell a lot of tokens, and will choose to sell even below the price they bought. Anti-dump feature can be called Anti-Panic feature. Reopen and implement thos option.

The question of who decides how much to restrict with Anti-Panic — is solved by ControlContract. This would be an ownerOnly set of methods. The owner can set taxes and restrictions, and in our ITR contract we will renounce ownership. But in other TradedTokens the owner can be a ControlContract where people might vote depending on how much of the token they hold.
