### ISSUE TITLE
Add presale option

### ISSUE THREAD

**Issue by EGreg** [Intercoin/TradedTokenContract#17]
So we want to allow the token to have presales for a specific price. This will make it so that some launchpad or crowdfunding platform can collect money, convert it to USDT and send to the smart contract, and receive the minted tokens to send out.

Please define the following function:

```
function presaleAdd(address, amount) onlyBeforeInitialLiquidity onlyOwner {
   mint(address, amount);
   emit Presale(address, amount):
}

// anyone can call this
function presaleBurnRemaining(address) {
    endTime = call(address, keccak(“endTime”));
    if (block.timestamp > endTime) {
      burn(address, balanceOf(presale));
    }
}
```

The most appropriate contract to use for this would be FundContract. That way anyone can see that all the tokens were sold for specific prices, and when.

owner of presale SHOULD renounce ownership so they cannot withdrawAll() !

**Comment by artman325** [comment]
> owner of presale SHOULD renounce ownership so they cannot withdrawAll() !

what's winthdrawAll?   `presaleBurnRemaining` can be called by everyone, even after presale is over

**Comment by EGreg** [comment]
withdrawAll() is called by owner, to withdraw tokens.

but presaleBurnRemaining can be called by everyone
let's allow anyone to call it 1 hour before the `endTime` (third parameter of presaleAdd can be uint32 duration)
So this way the public can guarantee that the presale contract owner (e.g. of FundContract) won't take the tokens.

**Comment by artman325** [comment]
so workflow are folliwing:
deployer deployed TradedToken contract and can add some presale tokens to any contract (implemented interface IPresale)  before 
- adding initial liquidty 
- (block.timestamp < endTime - minimumPresaleTimeAmount)

now Presale contract(for example FundContract can be trade tokens with special price).
**Note**: that users can add liquidity himself bypassing the TradedToken contract. There are no any checks for that.

And finally (after endTime passed) any users can burn such presale tokens by calling `presaleBurnRemaining(address)` and prevent further presales or manipulations with tokens(for eaxmple PresaleContract' owner can withdraw all tokens left to own account). what prevents do it in presale period?

Anyway doing exactly that described above.
except:
- withdrawAll()
- - okay it will be called of TradedToken's owner
- - What's will do? will burn all pre-sale tokens that was minted before? or only after endTime passed?  In both cases need to store contract addresses in `presaleAdd` , but there no any code there

**Comment by EGreg** [comment]
Good questions. I have made an issue for FundContract to address it: adding `ownerCanWithdraw` method https://github.com/Intercoin/FundContract/issues/14

You have a good point regarding "anyone can add liquidity". Let's disallow anyone adding liquidity before `addInitialLiquidity` method was called. This can be accomplished by blocking transfer of tokens to any UniSwap pair involving our token until addInitialLiquidity is called. 

How do we know that the target is a uniswap pair?
1) it's a contract, with code size > 0
2) we can check `token0` and `token1` on it, and if one of them is our token, we revert

**Comment by artman325** [comment]
disallowed anyone adding liquidity before addInitialLiquidity method was called
