### ISSUE TITLE
Make minimums "softer" allowing OTC but preventing sending to exchanges

### ISSUE THREAD

**Issue by EGreg** [Intercoin/TradedTokenContract#41]
We want to make a "softer" lock-up that allows addresses to send to each other for "over-the-counter" sales, but not to exchanges.

With MaxHolders, of course, addresses, can't send to others that have 0 balance. But they can send to addresses that have some balance.

Exchanges will be defined as addresses that received at least 4 transfers. So please have a public mapping:

`mapping receivedTransfersCount(address => uint256)`

Maybe there is another mapping where we can stow this. It only needs to be `uint2` actually, two bits. We would be wasting 256 bits. Ideally, to save `sstore` gas, we could store this inside the `balance` mapping, as one byte. But then we'd have to override internal OpenZeppelin methods like `balanceOf()` to mask it out with "& 0xFFFFFFFFFC". In any case it's not so bad because sstore in an existing slot isn't as expensive, and also because as long as we are using Polygon and Binance Smart chain, SSTORE is far cheaper.

Anyway, on every transfer to a smart contract address, you would increment this `receivedTransfersCount`. Once it hits 4 it's considered an "exchange" (even if it's a staking pool or something). And after 4 stop incrementing, especially if you are using 2 bits to store it somewhere.

Anyway, now during `_beforeTokenTransfer` you should check:

```
(minimumFrom, remainingTimeUntilEnd) = minimumsGet(from);
if (minimum > 0) {
  if (receivedTransfersCount[to] >= 4 && _balanceOf[from] - amount < minimumFrom) {
    revert CantSendToExchangeYet();
  }
  uint256 minimumTo = minimumsGet(to);
  minimumsSet(to, minimumTo + min(minimumsFrom, amount, remainingTimeUntilEnd);
  minimumsSet(from, minimumFrom - amount, remainingTimeUntilEnd); // transferred some minimum to recipient
}
```

So this way people can send to each other, but the minimum, if any would be transferred to recipient. All minimums are gradual, in this case. It means people can increasingly send to exchanges. But the minimums might be spread around.

**Comment by artman325** [comment]
did in branch : "41-make-minimums-softer"
exceed contract size and stop until there is enough time

**Comment by artman325** [comment]
did it after migration in the [commit:ca50f64921e4313f7a5d59ee95f27babaed13cdb](https://github.com/Intercoin/TradedTokenContract/commit/ca50f64921e4313f7a5d59ee95f27babaed13cdb)
