### ISSUE TITLE
Implement a way to pause the buy function

### ISSUE THREAD

**Issue by EGreg** [Intercoin/TradedTokenContract#49]
The buy function allows people to buy newly minted `TradedToken` from the smart contract. In some cases, managers may want to pause this, e.g. for regulatory compliance. So please implement in `TradedToken`:

```
bool buyPaused; // don't waste a slot, put it next to other bools

function pauseBuy(bool status) {
   buyPaused = status;
}
```

and add this:

```
function buy() {
   if (buyPaused) {
      revert BuyPaused();
   }
   // ... the rest of the function
}
```

finally, in `DistributionManager` please implement this function:

```
function buyPaused (status) ownerOnly {
    ITradedToken(tradedToken).buyPaused(status);
}
```

**Comment by EGreg** [comment]
@artman325 I coded it, you can close this after you tested it

**Comment by artman325** [comment]
moved suggestion into separated branch from master
Commits:
2afa16faf9e2c7e470295b9881908f0ef6034e5a Improved buy/sell logic and added to availableToClaim
71efeee09ebd7f51aaec4e170e1f37e473acf271 Implemented buy/sell and cleaned up memory layout

**Comment by artman325** [comment]
it was already present at the code. commit : [ca50f64921e4313f7a5d59ee95f27babaed13cdb](https://github.com/Intercoin/TradedTokenContract/commit/ca50f64921e4313f7a5d59ee95f27babaed13cdb)
BUT
keep in mind that pauseBuy method just prevent functionality of buy tokens through "buy" method, and distribute and claim manager interact with traded tokens through claim method only
