### ISSUE TITLE
Ownership and Managers

### ISSUE THREAD

**Issue by EGreg** [Intercoin/TradedTokenContract#7]
Please remove AccessControl from OpenZeppelin and only have Ownable from OpenZeppelin. We will call renounceOwnership after we set up managers.

Let's just have a function `addManager(address) managerOnly` which will modify private `_isManager` mapping and push to public `managers` array. Any manager can add more managers, but cannot remove them. Owner and Managers are the only ones who can call `claim()` and `addLiquidity()`, subject to limits logic. Make the `managerOnly` modifier which just checks the private `isManager` mapping.

**Comment by artman325** [comment]
ok will add following
- modifier managerOnly 
- function addManager(address) managerOnly
- mapping(address => uint64) managers;   // like address=>timestamp(when was added)

do:
- will add `managerOnly` modifier to `claim()` and `addLiquidity()`

**UPD** will change `managerOnly` => `onlyManagers`  to be consistent with onlyOwner, etc

**Comment by artman325** [comment]
did it in [last commit, branch 1 version2 ](https://github.com/Intercoin/TradedTokenContract/commit/868b3f1ddfbd1ba9f04f910de593b46ca719a7c5)
