### ISSUE TITLE
feature "sendback"

### ISSUE THREAD

**Issue by artman325** [Intercoin/TradedTokenContract#76]
We should allow persons to send back to the exchange which they received it from. For a few days (not more than that)
like that
```
on transfer:
  if (exchanges[from]) 
    canSendBack[address] = amount;
    canSendBackUntilTime[address] = block.timestamp + initParams.sendBackDuration;
```

**Notes:**
1. every further exchanges will override previous  `canSendBack[address].`
for example, first time he receives 100 tokens, and second - only 1. 
He will send back only 1   not 100.

2. any successful transfer (except this exchange) should reset to zero variable `canSendBack[address]` to prevent manipulation

**Comment by EGreg** [comment]
I updated to a different issue
