### ISSUE TITLE
Helper Contract

### ISSUE THREAD

**Issue by EGreg** [Intercoin/TradedTokenContract#8]
Make sure that `claim(amount, address)` a version that accepts the `address` parameter. Anyway, the internal `_mint(amount, address)` function should always expect a recipient address.

Due to UniSwap refusing to send results of the swap to the ERC20's own contract address, we have to create an auxiliary contract with one method:    `swapAndAddLiquidity(tradedTokenAmount, reserveTokenAmount) mainOnly`. This will be only callable by the contract which created it. Maybe we should also have a version which doesn't take any parameters, but just calls `ERC20(tradedToken).balanceOf(this)` and `ERC20(reserveToken).balanceOf(this)`, although that may take more gas.

The `addLiquidity(tradedTokenAmount)` function will `mint` this amount of tokens to the helper contract, and then call `swapAndAddLiquidity()` on it, forwarding the rest of the gas. That contract, in turn, will send the square root (or whatever exact amount of tokens) to the UniSwap pair, and call `swap()` on it. After that, it will call `addLiquidity` on the UniSwap pair, and return the result. The main contract should forward any error encountered to the user, otherwise it will succeed and issue an event from itself called `LiquidityAdded` with information like `tradedTokenAmount` and `reserveTokenAmount`.

**Comment by artman325** [comment]
i have created [Liquidity.sol](https://github.com/Intercoin/TradedTokenContract/blob/1-version2/contracts/Liquidity.sol)
to added liquidity.
so erc777(`Main.sol`) send own tokens and reserved tokens to this contract and it just add to liquidity.
swap and other functional are left in `Main.sol` because have a lot of settings
